version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Etc/UTC"
    labels:
      - maintenance
      - dependencies
